import "@/bootstrap.js";
import "./assets/main.css";

import { createApp } from "vue";
import { createPinia } from "pinia";

import App from "./App.vue";
import router from "./router";

import ValidationError from "@/components/ValidationError.vue";
import IconSpinner from "@/components/IconSpinner.vue";
import AlertMessage from "@/components/AlertMessage.vue";
import { TailwindPagination } from "laravel-vue-pagination";
import Multiselect from "vue-multiselect";
import OpenedEyeIcon from "@/components/OpenedEyeIcon.vue";
import ClosedEyeIcon from "@/components/ClosedEyeIcon.vue";
import PulseLoader from "vue-spinner/src/PulseLoader.vue";
import AppraisalRecordSection from "@/views/User/Partials/AppraisalRecordSection.vue";
import UserSearch from "@/components/UserSearch.vue";
import AppraiseeSection from "@/views/Appraisal/Partials/AppraiseeSection.vue";
import AppraiserSection from "@/views/Appraisal/Partials/AppraiserSection.vue";
import ApproverSection from "@/views/Appraisal/Partials/ApproverSection.vue";
import SelectAppraiseeModal from "@/views/Appraisal/Modals/SelectAppraiseeModal.vue";
import SelectAppraiserModal from "@/views/Appraisal/Modals/SelectAppraiseeModal.vue";
import SelectApproverModal from "@/views/Appraisal/Modals/SelectApproverModal.vue";
import UserSearchLite from "@/components/UserSearchLite.vue";
import UserCard from "@/components/UserCard.vue";
import ApproverCard from "@/components/ApproverCard.vue";
const app = createApp(App);

app.use(createPinia());
app.use(router);
app.component("ValidationError", ValidationError);
app.component("IconSpinner", IconSpinner);
app.component("AlertMessage", AlertMessage);
app.component("TailwindPagination", TailwindPagination);
app.component("Multiselect", Multiselect);
app.component("OpenedEyeIcon", OpenedEyeIcon);
app.component("ClosedEyeIcon", ClosedEyeIcon);
app.component("pulse-loader", PulseLoader);
app.component("AppraisalRecordSection", AppraisalRecordSection);
app.component("UserSearch", UserSearch);
app.component("UserSearchLite", UserSearchLite);
app.component("AppraiseeSection", AppraiseeSection);
app.component("AppraiserSection", AppraiserSection);
app.component("ApproverSection", ApproverSection);
app.component("SelectAppraiseeModal", SelectAppraiseeModal);
app.component("SelectAppraiserModal", SelectAppraiserModal);
app.component("SelectApproverModal", SelectApproverModal);
app.component("UserCard", UserCard);
app.component("ApproverCard", ApproverCard);
app.mount("#app");
